/* The following code was generated by JFlex 1.4.3 on 9/22/22, 1:15 AM */

package lexer;
import lexer.Token;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/22/22, 1:15 AM from the specification file
 * <tt>./src/lexer/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\53\1\45"+
    "\2\0\1\53\1\55\1\0\1\46\1\46\1\5\1\47\1\46\1\14"+
    "\1\12\1\4\1\10\7\11\2\7\1\46\1\46\1\52\1\50\1\51"+
    "\1\46\1\0\4\6\1\13\1\6\21\6\1\6\2\6\1\46\1\56"+
    "\1\46\1\53\1\6\1\0\1\15\1\21\1\25\1\32\1\23\1\33"+
    "\1\37\1\27\1\31\1\6\1\24\1\34\1\35\1\30\1\20\1\43"+
    "\1\6\1\22\1\26\1\17\1\16\1\44\1\41\1\36\1\42\1\40"+
    "\1\46\1\54\1\46\1\46\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\2\3\1\4\2\5\2\3\17\4"+
    "\1\6\6\3\1\7\1\10\1\11\1\12\1\0\1\1"+
    "\2\0\1\5\17\4\2\13\5\4\1\14\1\15\1\16"+
    "\1\17\1\12\2\0\1\1\31\4\1\12\1\0\1\2"+
    "\1\0\16\4\1\5\11\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\136\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a"+
    "\0\u0439\0\u0468\0\u0497\0\136\0\136\0\u04c6\0\u04f5\0\u0524"+
    "\0\u0553\0\u0582\0\u05b1\0\136\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u01a7\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u011a\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\136\0\136\0\136\0\136\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab"+
    "\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23"+
    "\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b"+
    "\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u0b04\0\u1086\0\u10b5\0\u10e4"+
    "\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c"+
    "\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4"+
    "\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\11\1\13\1\10\1\14\1\15\1\16\1\17\1\10"+
    "\1\20\1\21\1\22\1\10\1\23\1\24\2\10\1\25"+
    "\1\26\1\27\1\30\2\10\1\31\1\10\1\32\2\10"+
    "\1\33\1\34\1\35\1\36\1\7\1\37\1\40\1\7"+
    "\1\41\1\42\1\3\1\43\2\3\42\43\1\44\10\43"+
    "\1\45\61\0\1\5\60\0\1\46\1\47\42\0\1\35"+
    "\56\0\1\35\14\0\4\10\1\0\1\10\1\0\30\10"+
    "\20\0\1\50\3\11\1\51\1\50\1\0\30\50\20\0"+
    "\1\50\1\52\2\12\1\51\1\50\1\0\30\50\21\0"+
    "\3\53\61\0\1\35\33\0\2\35\13\0\4\10\1\0"+
    "\1\10\1\0\1\10\1\54\26\10\20\0\4\10\1\0"+
    "\1\10\1\0\13\10\1\55\14\10\20\0\4\10\1\0"+
    "\1\10\1\0\25\10\1\56\2\10\20\0\4\10\1\0"+
    "\1\10\1\0\5\10\1\57\22\10\20\0\4\10\1\0"+
    "\1\10\1\0\6\10\1\60\21\10\20\0\4\10\1\0"+
    "\1\10\1\0\13\10\1\61\3\10\1\62\1\10\1\63"+
    "\6\10\20\0\4\10\1\0\1\10\1\0\1\62\2\10"+
    "\1\64\6\10\1\65\15\10\20\0\4\10\1\0\1\10"+
    "\1\0\2\10\1\66\7\10\1\67\1\10\1\70\7\10"+
    "\1\71\3\10\20\0\4\10\1\0\1\10\1\0\13\10"+
    "\1\72\2\10\1\73\11\10\20\0\4\10\1\0\1\10"+
    "\1\0\3\10\1\74\2\10\1\75\21\10\20\0\4\10"+
    "\1\0\1\10\1\0\17\10\1\76\10\10\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\77\24\10\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\54\24\10\20\0\4\10"+
    "\1\0\1\10\1\0\12\10\1\100\15\10\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\101\24\10\61\0\2\35"+
    "\56\0\1\35\1\7\55\0\1\35\1\0\1\7\54\0"+
    "\1\35\3\0\1\35\52\0\1\35\4\0\1\35\1\0"+
    "\1\43\2\0\42\43\1\0\10\43\20\0\1\102\2\0"+
    "\1\103\5\0\1\104\14\0\1\105\11\0\1\46\1\106"+
    "\1\5\54\46\5\107\1\110\51\107\6\0\4\50\1\0"+
    "\1\50\1\0\30\50\21\0\3\52\1\51\52\0\1\50"+
    "\3\53\1\0\1\111\1\0\6\50\1\111\21\50\20\0"+
    "\4\10\1\0\1\10\1\0\2\10\1\112\25\10\20\0"+
    "\4\10\1\0\1\10\1\0\11\10\1\113\2\10\1\114"+
    "\13\10\20\0\4\10\1\0\1\10\1\0\26\10\1\115"+
    "\1\10\20\0\4\10\1\0\1\10\1\0\6\10\1\116"+
    "\21\10\20\0\4\10\1\0\1\10\1\0\2\10\1\117"+
    "\17\10\1\120\5\10\20\0\4\10\1\0\1\10\1\0"+
    "\1\10\1\121\26\10\20\0\4\10\1\0\1\10\1\0"+
    "\11\10\1\122\16\10\20\0\4\10\1\0\1\10\1\0"+
    "\2\10\1\123\25\10\20\0\4\10\1\0\1\10\1\0"+
    "\13\10\1\124\14\10\20\0\4\10\1\0\1\10\1\0"+
    "\1\125\27\10\20\0\4\10\1\0\1\10\1\0\1\126"+
    "\4\10\1\127\22\10\20\0\4\10\1\0\1\10\1\0"+
    "\3\10\1\130\24\10\20\0\4\10\1\0\1\10\1\0"+
    "\22\10\1\131\1\132\4\10\20\0\4\10\1\0\1\10"+
    "\1\0\14\10\1\133\13\10\20\0\4\10\1\0\1\10"+
    "\1\0\2\10\1\73\25\10\20\0\4\10\1\0\1\10"+
    "\1\0\1\10\1\134\26\10\20\0\4\10\1\0\1\10"+
    "\1\0\16\10\1\135\11\10\20\0\4\10\1\0\1\10"+
    "\1\0\3\10\1\136\24\10\20\0\4\10\1\0\1\10"+
    "\1\0\13\10\1\137\14\10\20\0\4\10\1\0\1\10"+
    "\1\0\14\10\1\140\13\10\20\0\4\10\1\0\1\10"+
    "\1\0\14\10\1\141\2\10\1\142\10\10\12\0\2\143"+
    "\1\5\54\143\5\107\1\144\55\107\1\145\1\144\51\107"+
    "\6\0\4\50\1\0\1\50\1\146\30\50\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\73\24\10\20\0\4\10"+
    "\1\0\1\10\1\0\14\10\1\147\13\10\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\150\24\10\20\0\4\10"+
    "\1\0\1\10\1\0\6\10\1\151\21\10\20\0\4\10"+
    "\1\0\1\10\1\0\1\152\27\10\20\0\4\10\1\0"+
    "\1\10\1\0\1\10\1\153\26\10\20\0\4\10\1\0"+
    "\1\10\1\0\14\10\1\154\13\10\20\0\4\10\1\0"+
    "\1\10\1\0\20\10\1\73\7\10\20\0\4\10\1\0"+
    "\1\10\1\0\6\10\1\73\21\10\20\0\4\10\1\0"+
    "\1\10\1\0\6\10\1\153\21\10\20\0\4\10\1\0"+
    "\1\10\1\0\2\10\1\155\6\10\1\72\16\10\20\0"+
    "\4\10\1\0\1\10\1\0\5\10\1\73\22\10\20\0"+
    "\4\10\1\0\1\10\1\0\2\10\1\156\25\10\20\0"+
    "\4\10\1\0\1\10\1\0\1\10\1\157\26\10\20\0"+
    "\4\10\1\0\1\10\1\0\5\10\1\72\22\10\20\0"+
    "\4\10\1\0\1\10\1\0\13\10\1\160\14\10\20\0"+
    "\4\10\1\0\1\10\1\0\6\10\1\161\21\10\20\0"+
    "\4\10\1\0\1\10\1\0\2\10\1\162\25\10\20\0"+
    "\4\10\1\0\1\10\1\0\4\10\1\140\23\10\20\0"+
    "\4\10\1\0\1\10\1\0\1\163\27\10\20\0\4\10"+
    "\1\0\1\10\1\0\1\72\27\10\20\0\4\10\1\0"+
    "\1\10\1\0\22\10\1\73\5\10\20\0\4\10\1\0"+
    "\1\10\1\0\17\10\1\122\10\10\20\0\4\10\1\0"+
    "\1\10\1\0\15\10\1\73\12\10\20\0\4\10\1\0"+
    "\1\10\1\0\1\164\27\10\12\0\2\143\1\0\54\143"+
    "\4\107\1\5\1\144\51\107\7\0\3\165\53\0\4\10"+
    "\1\0\1\10\1\0\22\10\1\131\5\10\20\0\4\10"+
    "\1\0\1\10\1\0\13\10\1\73\14\10\20\0\4\10"+
    "\1\0\1\10\1\0\15\10\1\166\12\10\20\0\4\10"+
    "\1\0\1\10\1\0\7\10\1\73\20\10\20\0\4\10"+
    "\1\0\1\10\1\0\5\10\1\150\22\10\20\0\4\10"+
    "\1\0\1\10\1\0\11\10\1\167\16\10\20\0\4\10"+
    "\1\0\1\10\1\0\14\10\1\170\13\10\20\0\4\10"+
    "\1\0\1\10\1\0\14\10\1\171\13\10\20\0\4\10"+
    "\1\0\1\10\1\0\10\10\1\72\17\10\20\0\4\10"+
    "\1\0\1\10\1\0\6\10\1\141\21\10\20\0\4\10"+
    "\1\0\1\10\1\0\3\10\1\172\24\10\20\0\4\10"+
    "\1\0\1\10\1\0\10\10\1\173\17\10\20\0\4\10"+
    "\1\0\1\10\1\0\1\10\1\174\26\10\20\0\4\10"+
    "\1\0\1\10\1\0\2\10\1\100\25\10\20\0\1\50"+
    "\3\165\1\0\1\50\1\0\30\50\20\0\4\10\1\0"+
    "\1\10\1\0\6\10\1\172\21\10\20\0\4\10\1\0"+
    "\1\10\1\0\2\10\1\175\25\10\20\0\4\10\1\0"+
    "\1\10\1\0\13\10\1\176\14\10\20\0\4\10\1\0"+
    "\1\10\1\0\10\10\1\73\17\10\20\0\4\10\1\0"+
    "\1\10\1\0\16\10\1\73\11\10\20\0\4\10\1\0"+
    "\1\10\1\0\12\10\1\73\15\10\20\0\4\10\1\0"+
    "\1\10\1\0\17\10\1\72\10\10\20\0\4\10\1\0"+
    "\1\10\1\0\6\10\1\125\21\10\20\0\4\10\1\0"+
    "\1\10\1\0\1\10\1\122\26\10\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5405];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\26\1\2\11\6\1\1\11"+
    "\2\1\1\0\1\1\2\0\27\1\4\11\1\1\2\0"+
    "\33\1\1\0\1\1\1\0\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

  StringBuffer string = new StringBuffer();

  public String lexeme;

  private Token createToken(KindToken kindToken){
    return new Token(yytext(),kindToken, yyline+1);
  }

  private Token createStringValueToken(KindToken kindToken, String value){
    return new Token(value, kindToken, yyline+1);
  }

  private LexicalError createLexicalError(String message){
    return new LexicalError(message,yyline+1);
    
  }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { string.append('\t');
          }
        case 16: break;
        case 5: 
          { lexeme=yytext(); return createToken(KindToken.LITERAL);
          }
        case 17: break;
        case 11: 
          { lexeme=yytext(); return createToken(KindToken.RESERVED_WORD);
          }
        case 18: break;
        case 4: 
          { lexeme=yytext(); return createToken(KindToken.IDENTIFIER);
          }
        case 19: break;
        case 8: 
          { yybegin(YYINITIAL); lexeme=string.toString(); return createStringValueToken(KindToken.LITERAL, string.toString());
          }
        case 20: break;
        case 2: 
          { /* ignore */
          }
        case 21: break;
        case 9: 
          { string.append('\\');
          }
        case 22: break;
        case 15: 
          { string.append('\"');
          }
        case 23: break;
        case 13: 
          { string.append('\r');
          }
        case 24: break;
        case 14: 
          { string.append('\n');
          }
        case 25: break;
        case 3: 
          { lexeme=yytext(); return createToken(KindToken.OPERATOR);
          }
        case 26: break;
        case 7: 
          { string.append( yytext() );
          }
        case 27: break;
        case 6: 
          { string.setLength(0); yybegin(STRING);
          }
        case 28: break;
        case 10: 
          { /*Ignore*/
          }
        case 29: break;
        case 1: 
          { throw createLexicalError("Illegal character <"+yytext()+">");
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
