/* The following code was generated by JFlex 1.4.3 on 9/21/22, 1:44 PM */

package lexer;
import lexer.Token;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/21/22, 1:44 PM from the specification file
 * <tt>./src/lexer/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\51\1\43"+
    "\2\0\1\51\1\53\1\0\1\44\1\44\1\5\1\45\1\44\1\12"+
    "\1\10\1\4\1\7\11\7\1\44\1\44\1\50\1\46\1\47\1\44"+
    "\1\0\4\6\1\11\1\6\21\6\1\6\2\6\1\44\1\54\1\44"+
    "\1\51\1\6\1\0\1\13\1\17\1\23\1\30\1\21\1\31\1\35"+
    "\1\25\1\27\1\6\1\22\1\32\1\33\1\26\1\16\1\41\1\6"+
    "\1\20\1\24\1\15\1\14\1\42\1\37\1\34\1\40\1\36\1\44"+
    "\1\52\1\44\1\44\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\2\3\1\4\1\5\2\3\17\4"+
    "\1\6\6\3\1\7\1\10\1\11\1\12\1\0\1\1"+
    "\1\0\1\5\17\4\2\13\5\4\1\14\1\15\1\16"+
    "\1\17\1\12\2\0\1\1\31\4\1\12\1\0\1\2"+
    "\1\0\16\4\1\5\11\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\132\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de"+
    "\0\u040b\0\u0438\0\132\0\132\0\u0465\0\u0492\0\u04bf\0\u04ec"+
    "\0\u0519\0\u0546\0\132\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0168"+
    "\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca"+
    "\0\u010e\0\u08f7\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\132"+
    "\0\132\0\132\0\132\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89"+
    "\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1"+
    "\0\u0f1e\0\u0f4b\0\u0a32\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c"+
    "\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u1167\0\u1194"+
    "\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc"+
    "\0\u1329\0\u1356\0\u1383\0\u13b0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\10\1\13\1\14\1\15\1\16\1\10\1\17\1\20"+
    "\1\21\1\10\1\22\1\23\2\10\1\24\1\25\1\26"+
    "\1\27\2\10\1\30\1\10\1\31\2\10\1\32\1\33"+
    "\1\34\1\35\1\7\1\36\1\37\1\7\1\40\1\41"+
    "\1\3\1\42\2\3\40\42\1\43\10\42\1\44\57\0"+
    "\1\5\56\0\1\45\1\46\40\0\1\34\54\0\1\34"+
    "\14\0\2\10\1\0\1\10\1\0\30\10\20\0\1\47"+
    "\1\11\1\50\1\47\1\0\30\47\21\0\1\51\57\0"+
    "\1\34\33\0\2\34\13\0\2\10\1\0\1\10\1\0"+
    "\1\10\1\52\26\10\20\0\2\10\1\0\1\10\1\0"+
    "\13\10\1\53\14\10\20\0\2\10\1\0\1\10\1\0"+
    "\25\10\1\54\2\10\20\0\2\10\1\0\1\10\1\0"+
    "\5\10\1\55\22\10\20\0\2\10\1\0\1\10\1\0"+
    "\6\10\1\56\21\10\20\0\2\10\1\0\1\10\1\0"+
    "\13\10\1\57\3\10\1\60\1\10\1\61\6\10\20\0"+
    "\2\10\1\0\1\10\1\0\1\60\2\10\1\62\6\10"+
    "\1\63\15\10\20\0\2\10\1\0\1\10\1\0\2\10"+
    "\1\64\7\10\1\65\1\10\1\66\7\10\1\67\3\10"+
    "\20\0\2\10\1\0\1\10\1\0\13\10\1\70\2\10"+
    "\1\71\11\10\20\0\2\10\1\0\1\10\1\0\3\10"+
    "\1\72\2\10\1\73\21\10\20\0\2\10\1\0\1\10"+
    "\1\0\17\10\1\74\10\10\20\0\2\10\1\0\1\10"+
    "\1\0\3\10\1\75\24\10\20\0\2\10\1\0\1\10"+
    "\1\0\3\10\1\52\24\10\20\0\2\10\1\0\1\10"+
    "\1\0\12\10\1\76\15\10\20\0\2\10\1\0\1\10"+
    "\1\0\3\10\1\77\24\10\57\0\2\34\54\0\1\34"+
    "\1\7\53\0\1\34\1\0\1\7\52\0\1\34\3\0"+
    "\1\34\50\0\1\34\4\0\1\34\1\0\1\42\2\0"+
    "\40\42\1\0\10\42\16\0\1\100\2\0\1\101\5\0"+
    "\1\102\14\0\1\103\11\0\1\45\1\104\1\5\52\45"+
    "\5\105\1\106\47\105\6\0\2\47\1\0\1\47\1\0"+
    "\30\47\20\0\1\47\1\51\1\0\1\107\1\0\6\47"+
    "\1\107\21\47\20\0\2\10\1\0\1\10\1\0\2\10"+
    "\1\110\25\10\20\0\2\10\1\0\1\10\1\0\11\10"+
    "\1\111\2\10\1\112\13\10\20\0\2\10\1\0\1\10"+
    "\1\0\26\10\1\113\1\10\20\0\2\10\1\0\1\10"+
    "\1\0\6\10\1\114\21\10\20\0\2\10\1\0\1\10"+
    "\1\0\2\10\1\115\17\10\1\116\5\10\20\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\117\26\10\20\0\2\10"+
    "\1\0\1\10\1\0\11\10\1\120\16\10\20\0\2\10"+
    "\1\0\1\10\1\0\2\10\1\121\25\10\20\0\2\10"+
    "\1\0\1\10\1\0\13\10\1\122\14\10\20\0\2\10"+
    "\1\0\1\10\1\0\1\123\27\10\20\0\2\10\1\0"+
    "\1\10\1\0\1\124\4\10\1\125\22\10\20\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\126\24\10\20\0\2\10"+
    "\1\0\1\10\1\0\22\10\1\127\1\130\4\10\20\0"+
    "\2\10\1\0\1\10\1\0\14\10\1\131\13\10\20\0"+
    "\2\10\1\0\1\10\1\0\2\10\1\71\25\10\20\0"+
    "\2\10\1\0\1\10\1\0\1\10\1\132\26\10\20\0"+
    "\2\10\1\0\1\10\1\0\16\10\1\133\11\10\20\0"+
    "\2\10\1\0\1\10\1\0\3\10\1\134\24\10\20\0"+
    "\2\10\1\0\1\10\1\0\13\10\1\135\14\10\20\0"+
    "\2\10\1\0\1\10\1\0\14\10\1\136\13\10\20\0"+
    "\2\10\1\0\1\10\1\0\14\10\1\137\2\10\1\140"+
    "\10\10\12\0\2\141\1\5\52\141\5\105\1\142\53\105"+
    "\1\143\1\142\47\105\6\0\2\47\1\0\1\47\1\144"+
    "\30\47\20\0\2\10\1\0\1\10\1\0\3\10\1\71"+
    "\24\10\20\0\2\10\1\0\1\10\1\0\14\10\1\145"+
    "\13\10\20\0\2\10\1\0\1\10\1\0\3\10\1\146"+
    "\24\10\20\0\2\10\1\0\1\10\1\0\6\10\1\147"+
    "\21\10\20\0\2\10\1\0\1\10\1\0\1\150\27\10"+
    "\20\0\2\10\1\0\1\10\1\0\1\10\1\151\26\10"+
    "\20\0\2\10\1\0\1\10\1\0\14\10\1\152\13\10"+
    "\20\0\2\10\1\0\1\10\1\0\20\10\1\71\7\10"+
    "\20\0\2\10\1\0\1\10\1\0\6\10\1\71\21\10"+
    "\20\0\2\10\1\0\1\10\1\0\6\10\1\151\21\10"+
    "\20\0\2\10\1\0\1\10\1\0\2\10\1\153\6\10"+
    "\1\70\16\10\20\0\2\10\1\0\1\10\1\0\5\10"+
    "\1\71\22\10\20\0\2\10\1\0\1\10\1\0\2\10"+
    "\1\154\25\10\20\0\2\10\1\0\1\10\1\0\1\10"+
    "\1\155\26\10\20\0\2\10\1\0\1\10\1\0\5\10"+
    "\1\70\22\10\20\0\2\10\1\0\1\10\1\0\13\10"+
    "\1\156\14\10\20\0\2\10\1\0\1\10\1\0\6\10"+
    "\1\157\21\10\20\0\2\10\1\0\1\10\1\0\2\10"+
    "\1\160\25\10\20\0\2\10\1\0\1\10\1\0\4\10"+
    "\1\136\23\10\20\0\2\10\1\0\1\10\1\0\1\161"+
    "\27\10\20\0\2\10\1\0\1\10\1\0\1\70\27\10"+
    "\20\0\2\10\1\0\1\10\1\0\22\10\1\71\5\10"+
    "\20\0\2\10\1\0\1\10\1\0\17\10\1\120\10\10"+
    "\20\0\2\10\1\0\1\10\1\0\15\10\1\71\12\10"+
    "\20\0\2\10\1\0\1\10\1\0\1\162\27\10\12\0"+
    "\2\141\1\0\52\141\4\105\1\5\1\142\47\105\7\0"+
    "\1\163\53\0\2\10\1\0\1\10\1\0\22\10\1\127"+
    "\5\10\20\0\2\10\1\0\1\10\1\0\13\10\1\71"+
    "\14\10\20\0\2\10\1\0\1\10\1\0\15\10\1\164"+
    "\12\10\20\0\2\10\1\0\1\10\1\0\7\10\1\71"+
    "\20\10\20\0\2\10\1\0\1\10\1\0\5\10\1\146"+
    "\22\10\20\0\2\10\1\0\1\10\1\0\11\10\1\165"+
    "\16\10\20\0\2\10\1\0\1\10\1\0\14\10\1\166"+
    "\13\10\20\0\2\10\1\0\1\10\1\0\14\10\1\167"+
    "\13\10\20\0\2\10\1\0\1\10\1\0\10\10\1\70"+
    "\17\10\20\0\2\10\1\0\1\10\1\0\6\10\1\137"+
    "\21\10\20\0\2\10\1\0\1\10\1\0\3\10\1\170"+
    "\24\10\20\0\2\10\1\0\1\10\1\0\10\10\1\171"+
    "\17\10\20\0\2\10\1\0\1\10\1\0\1\10\1\172"+
    "\26\10\20\0\2\10\1\0\1\10\1\0\2\10\1\76"+
    "\25\10\20\0\1\47\1\163\1\0\1\47\1\0\30\47"+
    "\20\0\2\10\1\0\1\10\1\0\6\10\1\170\21\10"+
    "\20\0\2\10\1\0\1\10\1\0\2\10\1\173\25\10"+
    "\20\0\2\10\1\0\1\10\1\0\13\10\1\174\14\10"+
    "\20\0\2\10\1\0\1\10\1\0\10\10\1\71\17\10"+
    "\20\0\2\10\1\0\1\10\1\0\16\10\1\71\11\10"+
    "\20\0\2\10\1\0\1\10\1\0\12\10\1\71\15\10"+
    "\20\0\2\10\1\0\1\10\1\0\17\10\1\70\10\10"+
    "\20\0\2\10\1\0\1\10\1\0\6\10\1\123\21\10"+
    "\20\0\2\10\1\0\1\10\1\0\1\10\1\120\26\10"+
    "\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5085];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\25\1\2\11\6\1\1\11"+
    "\2\1\1\0\1\1\1\0\27\1\4\11\1\1\2\0"+
    "\33\1\1\0\1\1\1\0\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

  StringBuffer string = new StringBuffer();

  public String lexeme;

  private Token createToken(KindToken kindToken){
    return new Token(yytext(),kindToken, yyline+1);
  }

  private Token createStringValueToken(KindToken kindToken, String value){
    return new Token(value, kindToken, yyline+1);
  }

  private LexicalError createLexicalError(String message){
    return new LexicalError(message,yyline+1);
    
  }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 148) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { string.append('\t');
          }
        case 16: break;
        case 5: 
          { lexeme=yytext(); return createToken(KindToken.LITERAL);
          }
        case 17: break;
        case 11: 
          { lexeme=yytext(); return createToken(KindToken.RESERVED_WORD);
          }
        case 18: break;
        case 4: 
          { lexeme=yytext(); return createToken(KindToken.IDENTIFIER);
          }
        case 19: break;
        case 8: 
          { yybegin(YYINITIAL); lexeme=string.toString(); return createStringValueToken(KindToken.LITERAL, string.toString());
          }
        case 20: break;
        case 2: 
          { /* ignore */
          }
        case 21: break;
        case 9: 
          { string.append('\\');
          }
        case 22: break;
        case 15: 
          { string.append('\"');
          }
        case 23: break;
        case 13: 
          { string.append('\r');
          }
        case 24: break;
        case 14: 
          { string.append('\n');
          }
        case 25: break;
        case 3: 
          { lexeme=yytext(); return createToken(KindToken.OPERATOR);
          }
        case 26: break;
        case 7: 
          { string.append( yytext() );
          }
        case 27: break;
        case 6: 
          { string.setLength(0); yybegin(STRING);
          }
        case 28: break;
        case 10: 
          { /*Ignore*/
          }
        case 29: break;
        case 1: 
          { throw createLexicalError("Illegal character <"+yytext()+">");
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
