
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 30 19:27:19 CST 2022
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARLITERAL = 25;
  public static final int SHORT = 16;
  public static final int LBRACKET = 39;
  public static final int MULT = 33;
  public static final int CONST = 6;
  public static final int CHAR = 5;
  public static final int OPINCDEC = 48;
  public static final int CASE = 4;
  public static final int CONTINUE = 7;
  public static final int INT = 13;
  public static final int FOR = 11;
  public static final int MINUS = 32;
  public static final int WRITE = 22;
  public static final int NUMBERLITERAL = 24;
  public static final int NOT = 44;
  public static final int AND = 43;
  public static final int SEMICOLON = 28;
  public static final int RPAR = 36;
  public static final int LBRACES = 41;
  public static final int RBRACES = 40;
  public static final int OR = 42;
  public static final int COMMA = 27;
  public static final int DIV = 34;
  public static final int MAIN = 20;
  public static final int IF = 12;
  public static final int DOT = 2;
  public static final int ID = 23;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 38;
  public static final int EQUAL = 30;
  public static final int error = 1;
  public static final int OPEQUALITY = 46;
  public static final int MOD = 35;
  public static final int OPASSIGNMENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 18;
  public static final int SWITCH = 17;
  public static final int COLON = 29;
  public static final int ELSE = 10;
  public static final int READ = 21;
  public static final int WHILE = 19;
  public static final int OPRELATIONAL = 45;
  public static final int DEFAULT = 8;
  public static final int SUM = 31;
  public static final int LONG = 14;
  public static final int LPAR = 37;
  public static final int STRING = 26;
  public static final int DO = 9;
}

